const usuarios = [
  {
    nombre: 'Luis',
    apellido: 'Garcia',
    id: '123',
    tipo_usuario: '1',
    email: 'luis@correo.com',
    password: '123',
    direccion: 'calle 12',
    telefono: '3001234567',
    token: 'EstoDeberiaEstarCifradoYSerUnico',
    fecha_ingreso: '2021-02-15',
    salario: '500',
    cargo: 'Administrador Funcional',
  },
  {
    nombre: 'Andrea',
    apellido: 'Lopez',
    id: '456',
    tipo_usuario: '2',
    email: 'andrea@correo.com',
    password: '123',
    direccion: 'carrera 45',
    telefono: '3151234567',
    token: 'EstoDeberiaEstarCifradoYSerUnico',
    fecha_ingreso: '2021-02-15',
    salario: '200',
    cargo: 'Auxiliar Nomina',
  },
  {
    nombre: 'Wilson',
    apellido: 'Fernandez',
    id: '789',
    tipo_usuario: '3',
    email: 'wilson@correo.com',
    password: '123',
    direccion: 'Av Olaya',
    telefono: '3201234567',
    token: 'EstoDeberiaEstarCifradoYSerUnico',
    echa_ingreso: '2021-02-15',
    salario: '800',
    cargo: 'Jefe de Operaciones',
  },
];

module.exports = usuarios;
